---
# handlers file for nomad
 - name: restart nomad
   service:
           name: nomad
           state: restarted
           enabled: true
 - name: reload systemd
   command: systemctl daemon-reload
