---
# handlers file for consul
 - name: restart consul
   service:
           name: consul
           state: restarted
           enabled: true
 - name: reload systemd
   command: systemctl daemon-reload
